name: ultimate_alarm_clock
version: 0.2.1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: 3.22.2

dependencies:
  firebase_core: ^2.27.0

  screen_state: ^4.0.0
  screen_brightness: ^0.2.2+1
  cupertino_icons: ^1.0.2
  win32: ^5.2.0
  get: 4.6.6
  get_storage: ^2.1.1
  flutter_time_picker_spinner: ^2.0.0
  cloud_firestore: ^4.17.5
  intl: ^0.18.0
  latlong2: ^0.8.1
  flutter_map: ^4.0.0
  fl_location: ^2.0.0+1
  flutter_fgbg: ^0.3.0
  flutter_svg: ^2.0.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  async: ^2.10.0
  flutter_secure_storage: ^8.0.0
  weather: ^2.0.1
  shake: ^2.2.0
  numberpicker: ^2.1.2
  mobile_scanner: 3.5.5
  permission_handler: ^11.0.1
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.0
  flutter_expandable_fab: ^1.8.1
  vibration: ^1.8.1
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  sensors_plus: ^1.4.1
  rxdart: ^0.27.7
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.8
  fluttertoast: ^8.2.5
  path_provider: ^2.1.1
  audio_session: ^0.1.18
  uuid: ^4.3.3
  pedometer: ^4.0.1
  flutter_volume_controller: ^1.3.1
  sqflite: ^2.3.2
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  firebase_auth: ^4.17.8
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  android_intent_plus: ^5.0.2
  telephony: ^0.2.0
  intl_phone_number_input: ^0.7.4
  firebase_messaging: ^14.7.19
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^16.3.2
  collection: ^1.18.0
  cloud_functions: ^4.7.6

dev_dependencies:
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: "assets/images/splashscreen.png"
  color_dark: "#16171C"
  image_dark: "assets/images/splashscreen.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher-playstore.png"

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
  uses-material-design: true
  assets:
    - assets/images/
    - assets/ringtones/
