name: ultimate_alarm_clock
version: 0.5.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: 3.16.0

dependencies:
  firebase_core: ^2.8.0
  screen_state: ^2.0.0
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_time_picker_spinner: ^2.0.0
  cloud_firestore: ^4.4.5
  intl: ^0.18.0
  latlong2: ^0.8.1
  flutter_map: ^4.0.0
  fl_location: ^2.0.0+1
  flutter_fgbg: ^0.3.0
  flutter_svg: ^2.0.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  async: ^2.10.0
  flutter_secure_storage: ^8.0.0
  weather: ^2.0.1
  shake: ^2.2.0
  numberpicker: ^2.1.2
  mobile_scanner: ^3.5.2
  permission_handler: ^11.0.1
  google_sign_in: ^6.0.2
  url_launcher: ^6.1.11
  flutter_expandable_fab: ^1.8.1
  vibration: ^1.8.1
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  rxdart: ^0.27.7
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.8
  fluttertoast: ^8.2.4
  path_provider: ^2.1.1
  audio_session: ^0.1.18

dev_dependencies:
  flutter_lints: ^2.0.3
  isar_generator: ^3.1.0+1
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: "assets/images/splashscreen.png"
  color_dark: "#16171C"
  image_dark: "assets/images/splashscreen.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher-playstore.png"

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
  uses-material-design: true
  assets:
    - assets/images/
